name: Python package workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install colorama requests

    - name: Run tests
      run: |
        pytest

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      run: |
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    - name: Bump version to 0.0.25
      run: |
        python -c "import re; file = open('setup.py', 'r'); text = file.read(); file.close(); file = open('setup.py', 'w'); file.write(re.sub(r'version=\"\d+\.\d+\.\d+\"', 'version=\"0.0.25\"', text)); file.close()"
